version: "3.7"

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./local_test.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app.create_app:create_app()"
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - benford-app

networks:
  my-network:
